services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes: []

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes: []

